CREATE TABLE `DADOS2` (
  `DADO_ID_PK` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `DADO_NOME` VARCHAR(100) DEFAULT NULL,
  `DADO_CPF` VARCHAR(11) UNIQUE NOT NULL,
  `DADO_DTNASC` DATE DEFAULT NULL,
  `DADO_LOGRADOURO` VARCHAR(100) DEFAULT NULL,
  `DADO_COMPLEMENTO` VARCHAR(100) DEFAULT NULL,
  `DADO_NUM_CASA` VARCHAR(10) DEFAULT NULL,
  `DADO_BAIRRO` VARCHAR(100) DEFAULT NULL,
  `DADO_CIDADE` VARCHAR(70) DEFAULT NULL,
  `DADO_UF` VARCHAR(2) DEFAULT NULL,
  `DADO_CEP` VARCHAR(8) DEFAULT NULL,
  `DADO_TEL01` VARCHAR(10) DEFAULT NULL,
  `DADO_TEL02` VARCHAR(11) DEFAULT NULL,
  `DADO_EMAIL` VARCHAR(50) DEFAULT NULL,
  `DADO_OBSERVACAO` TEXT DEFAULT NULL,
  `DADO_DTINSERT` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `DADO_DTUPDATE` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

